### PR TITLE
Add 1.5beta1

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
```console
$ ./generate-stackbrew-library.sh
# maintainer: InfoSiftr <github@infosiftr.com> (@infosiftr)
# maintainer: Johan Euphrosine <proppy@google.com> (@proppy)

1.3.3: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.3
1.3: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.3

1.3.3-onbuild: git://github.com/docker-library/golang@4d4b14164e50c089a09b9364697749dc7f764824 1.3/onbuild
1.3-onbuild: git://github.com/docker-library/golang@4d4b14164e50c089a09b9364697749dc7f764824 1.3/onbuild

1.3.3-cross: git://github.com/docker-library/golang@acc4ed5ba8dfad17bd484ac858950bc6a6f9acde 1.3/cross
1.3-cross: git://github.com/docker-library/golang@acc4ed5ba8dfad17bd484ac858950bc6a6f9acde 1.3/cross

1.3.3-wheezy: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.3/wheezy
1.3-wheezy: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.3/wheezy

1.4.2: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.4
1.4: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.4
1: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.4
latest: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.4

1.4.2-onbuild: git://github.com/docker-library/golang@396f40c6188614c7acd6d8299a0ea71030a056a6 1.4/onbuild
1.4-onbuild: git://github.com/docker-library/golang@396f40c6188614c7acd6d8299a0ea71030a056a6 1.4/onbuild
1-onbuild: git://github.com/docker-library/golang@396f40c6188614c7acd6d8299a0ea71030a056a6 1.4/onbuild
onbuild: git://github.com/docker-library/golang@396f40c6188614c7acd6d8299a0ea71030a056a6 1.4/onbuild

1.4.2-cross: git://github.com/docker-library/golang@396f40c6188614c7acd6d8299a0ea71030a056a6 1.4/cross
1.4-cross: git://github.com/docker-library/golang@396f40c6188614c7acd6d8299a0ea71030a056a6 1.4/cross
1-cross: git://github.com/docker-library/golang@396f40c6188614c7acd6d8299a0ea71030a056a6 1.4/cross
cross: git://github.com/docker-library/golang@396f40c6188614c7acd6d8299a0ea71030a056a6 1.4/cross

1.4.2-wheezy: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.4/wheezy
1.4-wheezy: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.4/wheezy
1-wheezy: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.4/wheezy
wheezy: git://github.com/docker-library/golang@1a422afd7db928a821e97906ed27ed606e2f072a 1.4/wheezy

1.5beta1: git://github.com/docker-library/golang@991f9c955e9b9874ed3c485a9ad8670082fb7702 1.5
1.5: git://github.com/docker-library/golang@991f9c955e9b9874ed3c485a9ad8670082fb7702 1.5

1.5beta1-onbuild: git://github.com/docker-library/golang@991f9c955e9b9874ed3c485a9ad8670082fb7702 1.5/onbuild
1.5-onbuild: git://github.com/docker-library/golang@991f9c955e9b9874ed3c485a9ad8670082fb7702 1.5/onbuild
```

**Comment by tianon** [comment]
I'm working on making `update.sh` better so we can track these properly too. :+1:

**Comment by tianon** [comment]
```console
$ ./update.sh
+ sed -ri 's/^(ENV GOLANG_VERSION) .*/\1 1.3.3/' 1.3/Dockerfile
+ sed -ri 's/^(FROM golang):.*/\1:1.3.3/' 1.3/cross/Dockerfile 1.3/onbuild/Dockerfile 1.3/wheezy/Dockerfile
+ cp go-wrapper 1.3/
+ cp 1.3/Dockerfile 1.3/go-wrapper 1.3/wheezy/
+ sed -i 's/^FROM .*/FROM buildpack-deps:wheezy-scm/' 1.3/wheezy/Dockerfile
+ sed -ri 's/^(ENV GOLANG_VERSION) .*/\1 1.4.2/' 1.4/Dockerfile
+ sed -ri 's/^(FROM golang):.*/\1:1.4.2/' 1.4/cross/Dockerfile 1.4/onbuild/Dockerfile 1.4/wheezy/Dockerfile
+ cp go-wrapper 1.4/
+ cp 1.4/Dockerfile 1.4/go-wrapper 1.4/wheezy/
+ sed -i 's/^FROM .*/FROM buildpack-deps:wheezy-scm/' 1.4/wheezy/Dockerfile
+ sed -ri 's/^(ENV GOLANG_VERSION) .*/\1 1.5beta1/' 1.5/Dockerfile
+ sed -ri 's/^(FROM golang):.*/\1:1.5beta1/' 1.5/onbuild/Dockerfile
+ cp go-wrapper 1.5/
```

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
