### PR TITLE
Add support for Windows Server 1803

### PR DESCRIPTION
**Pull request by nwt**

### CODE REVIEW

**Comment by nwt** [comment]
Could someone have a look at this?

**Comment by tianon** [comment]
The PR looks great, but the official images don't have any 1803 infra set
up to actually build it yet. 😣

**Comment by tianon** [comment]
... and will also remove `powershell`, thus making it much more difficult to get Go installed.  See also https://github.com/docker-library/official-images/issues/3383.

**Comment by nwt** [comment]
@tianon: Is there anything I can do to help create the necessary infra?

**Comment by nwt** [comment]
@tianon: Anything I can do to help create the necessary infra?

**Comment by tianon** [comment]
Ok, got infra in order, rebased, added the new 1.11-rc from master, tested 1.10 successfully.  I think this is ready to go.  I'm going to merge without waiting for Travis/AppArmor since those won't test anything this PR adds/adjusts anyhow. :+1:

**Pull request merged**
