### PR TITLE
change 1.11rc to 1.11

### PR DESCRIPTION
**Pull request by tao12345666333**
Go 1.11 is released at 24 August 2018.

https://blog.golang.org/go1.11

close: https://github.com/docker-library/golang/issues/233

### CODE REVIEW

**Comment by michael-k** [comment]
You forgot to update the aliases: https://github.com/docker-library/golang/blob/1a7381c32220091f35bd76e34bc28af251954acb/generate-stackbrew-library.sh#L4-L7

**Comment by tao12345666333** [comment]
@michael-k  yes, updated.

**Comment by kolyshkin** [comment]
@tao12345666333 can you please squash the two commits into one? It does not make sense to have it separately.

**Comment by billinghamj** [comment]
It's normally possible for contributors to make the edits, if you want to avoid waiting

**Comment by tao12345666333** [comment]
Updated.

**Comment by billinghamj** [comment]
@kolyshkin Would it be possible to get this merged today please?

**Comment by rocketbitz** [comment]
any timeline for when this will make it to https://hub.docker.com/r/library/golang/tags/ ?

**Comment by pierrre** [comment]
@rocketbitz it's available

**Comment by michael-k** [comment]
@rocketbitz https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/golang/93/console

**Pull request merged**
