### PR TITLE
Add alpine:3.11

### PR DESCRIPTION
**Pull request by sapk**
It should:

- add golang:1.12-alpine3.11
- add golang:1.13-alpine3.11
- add golang:1.14-rc-alpine3.11
- remove golang:1.12-alpine3.9
- remove golang:1.14-rc-alpine3.10
- set alpine 3.11 as default for alpine base.

Release note: https://alpinelinux.org/posts/Alpine-3.11.0-released.html

### CODE REVIEW

**Comment by thaJeztah** [comment]
> remove golang:1.12-alpine3.9

Wondering if the alpine 3.9 variant should be kept for existing (non-rc) Go releases

/cc @ncopa @tianon

**Comment by sapk** [comment]
@thaJeztah Good question. 
For details, support for 3.9 end at 2020-11-01so maybe it should be kept. 
I currently, I based myself on my previous PR https://github.com/docker-library/golang/pull/285

**Comment by tianon** [comment]
We've traditionally kept a maximum of two versions here because for Alpine we have to build from source so supporting more than two is a bit heavier.

**Comment by tianon** [comment]
Thanks! :+1:

**Pull request merged**
