### PR TITLE
go-wrapper for alpine variant

### PR DESCRIPTION
**Pull request by xanadros**
Added a posix compliant version of the go-wrapper script.

There were only minor changes to the original script to accommodate array usage under /bin/sh

### CODE REVIEW

**Comment by tianon** [comment]
Awesome, thanks for proposing this!  I'm including the diff below so we can review with more context a bit later:
```diff
diff --git a/dev/fd/63 b/dev/fd/62
--- a/dev/fd/63
+++ b/dev/fd/62
@@ -1,46 +1,44 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 
 usage() {
 	base="$(basename "$0")"
 	cat <<EOUSAGE
-
 usage: $base command [args]
-
 This script assumes that is is run from the root of your Go package (for
 example, "/go/src/app" if your GOPATH is set to "/go").
-
 In Go 1.4, a feature was introduced to supply the canonical "import path" for a
 given package in a comment attached to a package statement
 (https://golang.org/s/go14customimport).
-
 This script allows us to take a generic directory of Go source files such as
 "/go/src/app" and determine that the canonical "import path" of where that code
 expects to live and reference itself is "github.com/jsmith/my-cool-app".  It
 will then ensure that "/go/src/github.com/jsmith/my-cool-app" is a symlink to
 "/go/src/app", which allows us to build and run it under the proper package
 name.
-
 For compatibility with versions of Go older than 1.4, the "import path" may also
 be placed in a file named ".godir".
-
 Available Commands:
-
   $base download
   $base download -u
     (equivalent to "go get -d [args] [godir]")
-
   $base install
   $base install -race
     (equivalent to "go install [args] [godir]")
-
   $base run
   $base run -app -specific -arguments
     (assumes "GOPATH/bin" is in "PATH")
-
 EOUSAGE
 }
 
+# Workaround for using the $@ for an array in a non bash environment
+# This func allows you to save the current arguments to a variable for future use.
+# Usage: args=$(save "$@")
+save () {
+for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
+echo " "
+}
+
 # "shift" so that "$@" becomes the remaining arguments and can be passed along to other "go" subcommands easily
 cmd="$1"
 if ! shift; then
@@ -50,7 +48,7 @@ fi
 
 goDir="$(go list -e -f '{{.ImportComment}}' 2>/dev/null || true)"
 
-if [ -z "$goDir" -a -s .godir ]; then
+if [ -z "$goDir" ] && [ -s .godir ]; then
 	goDir="$(cat .godir)"
 fi
 
@@ -69,24 +67,30 @@ if [ "$goDir" ]; then
 else
 	goBin="$(basename "$dir")" # likely "app"
 fi
-
 case "$cmd" in
 	download)
-		execCommand=( go get -v -d "$@" )
-		if [ "$goDir" ]; then execCommand+=( "$goDir" ); fi
-		set -x; exec "${execCommand[@]}"
+		args=$(save "$@")
+		set -- go get -v -d
+		# args seems to have a space in it if they are empty.  Check to make sure it's not just a space.
+		if [ "$args" != " " ]; then set -- "$@" "$args"; fi
+		if [ "$goDir" ]; then set -- "$@" "$goDir"; fi
+		set -x; exec "$@"
 		;;
-		
+
 	install)
-		execCommand=( go install -v "$@" )
-		if [ "$goDir" ]; then execCommand+=( "$goDir" ); fi
-		set -x; exec "${execCommand[@]}"
+		args=$(save "$@")
+		set -- go install -v
+		# args seems to have a space in it if they are empty.  Check to make sure it's not just a space.
+		if [ "$args" != " " ]; then set -- "$@" "$args"; fi
+		if [ "$goDir" ]; then set -- "$@" "$goDir"; fi
+		echo "$@"
+		set -x; exec "$@"
 		;;
-		
+
 	run)
 		set -x; exec "$goBin" "$@"
 		;;
-		
+
 	*)
 		echo >&2 'error: unknown command:' "$cmd"
 		usage >&2
```

**Comment by xanadros** [comment]
Forgot I had that change to the if goDir statement.  I think that was a shellcheck warning

"Prefer [ p ] && [ q ] as [ p -a q ] is not well defined."  [SC2166](https://github.com/koalaman/shellcheck/wiki/SC2166)

**Comment by xanadros** [comment]
I know it passes tests, but there is a problem with the script that I'm going to try working out.  It doesn't handle arguments at all.  I'll update the branch when I have something better.

**Comment by xanadros** [comment]
Any thoughts on this?  I didn't apply it to the 1.6 version, but can if you want.

**Pull request closed without merging**
