### PR TITLE
bump versions for security release 1.7.4 and 1.6.4

### PR DESCRIPTION
**Pull request by jmhodges**
See https://groups.google.com/forum/#!topic/golang-announce/2lP5z9i9ySY

### CODE REVIEW

**Comment by tianon** [comment]
Nice, thanks! :+1:

**Comment by jmhodges** [comment]
Oh, I see that docker library bot just made some similar commits right after this got merged. I guess I didn't understand what was meant by that "Automated update.sh" link in the README.

**Comment by jmhodges** [comment]
Is there also a bot that bumps the official-images repo, or should I be sending a PR over there (the docs I found don't quite say)? I'm not sure what the timeline is for a release.

**Comment by tianon** [comment]
PR is open at https://github.com/docker-library/official-images/pull/2411 -- just waiting for the Windows build test to finish and then it'll be building officially :+1:

**Comment by jmhodges** [comment]
Oh! Thank you!

**Pull request merged**
