### PR TITLE
Add "alpine" variant

### PR DESCRIPTION
**Pull request by tianon**
Size comparisons:

	golang              1.4                 562.7 MB
	golang              1.4-alpine          143 MB

	golang              1.5                 709.3 MB
	golang              1.5-alpine          262.3 MB

### CODE REVIEW

**Comment by tianon** [comment]
Woot, the `golang-hello-world` test passes too! :smile:

**Comment by yosifkit** [comment]
Seems fine to me, I assume a docs PR to describe the image and its limitations?

**Comment by tianon** [comment]
https://github.com/docker-library/docs/pull/386 is a start :smile:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
