### PR TITLE
Alpine 3.14

### PR DESCRIPTION
**Pull request by techknowlogick**
Fix https://github.com/docker-library/golang/issues/372

### CODE REVIEW

**Comment by techknowlogick** [comment]
CI Fail seems related to https://github.com/docker-library/golang/issues/359

**Comment by techknowlogick** [comment]
If anyone wants to take a look at CI fail I'm happy to give access to this branch, probably better if you create a new PR though so you don't need to wait on me for anything.

**Comment by tianon** [comment]
Ahahaha, it's the reverse of the problem in #359, I love it.  I'll take a look. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/golang/compare/68ce3330628f4d0a28a13254d98f5f4275b71c5b..6dd3e33358a28c4d352ec09528e4c77e8c61c235 is removing Alpine 3.12

https://github.com/docker-library/golang/compare/6dd3e33358a28c4d352ec09528e4c77e8c61c235..f300e60ca19c3b98cfcf01ca112af2ac10104320 is the actual fix

The end result is just codifying the two trouble situations -- Go 1.15 built against Go 1.16+ or Go 1.16+ built against Go 1.15 (where Alpine 3.13 represents Go 1.15 for one half of the comparisons).

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
