### PR TITLE
Add go1.6beta1

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Greeeeen :+1:

**Comment by tianon** [comment]
For reference:
```diff
diff --git a/1.5/Dockerfile b/1.6/Dockerfile
similarity index 87%
copy from 1.5/Dockerfile
copy to 1.6/Dockerfile
index dd7e9be..4149cd4 100644
--- a/1.5/Dockerfile
+++ b/1.6/Dockerfile
@@ -8,9 +8,9 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
                make \
        && rm -rf /var/lib/apt/lists/*
 
-ENV GOLANG_VERSION 1.5.2
+ENV GOLANG_VERSION 1.6beta1
 ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz
-ENV GOLANG_DOWNLOAD_SHA1 cae87ed095e8d94a81871281d35da7829bd1234e
+ENV GOLANG_DOWNLOAD_SHA1 5c02222a5ab348ae0f9244df95dea71781953749
 
 RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
        && echo "$GOLANG_DOWNLOAD_SHA1  golang.tar.gz" | sha1sum -c - \
diff --git a/1.5/alpine/Dockerfile b/1.6/alpine/Dockerfile
similarity index 93%
copy from 1.5/alpine/Dockerfile
copy to 1.6/alpine/Dockerfile
index d5e3978..cf3ffa7 100644
--- a/1.5/alpine/Dockerfile
+++ b/1.6/alpine/Dockerfile
@@ -1,8 +1,8 @@
 FROM alpine:3.2
 
-ENV GOLANG_VERSION 1.5.2
+ENV GOLANG_VERSION 1.6beta1
 ENV GOLANG_SRC_URL https://golang.org/dl/go$GOLANG_VERSION.src.tar.gz
-ENV GOLANG_SRC_SHA1 c7d78ba4df574b5f9a9bb5d17505f40c4d89b81c
+ENV GOLANG_SRC_SHA1 b19ab6ff440842d7518a24157704bedd14a453b1
 
 ENV GOLANG_BOOTSTRAP_VERSION 1.4.3
 ENV GOLANG_BOOTSTRAP_URL https://golang.org/dl/go$GOLANG_BOOTSTRAP_VERSION.src.tar.gz
diff --git a/go-wrapper b/1.6/go-wrapper
similarity index 100%
copy from go-wrapper
copy to 1.6/go-wrapper
diff --git a/1.4/onbuild/Dockerfile b/1.6/onbuild/Dockerfile
similarity index 93%
copy from 1.4/onbuild/Dockerfile
copy to 1.6/onbuild/Dockerfile
index e62e406..a854f4b 100644
--- a/1.4/onbuild/Dockerfile
+++ b/1.6/onbuild/Dockerfile
@@ -1,4 +1,4 @@
-FROM golang:1.4
+FROM golang:1.6
 
 RUN mkdir -p /go/src/app
 WORKDIR /go/src/app
diff --git a/1.5/wheezy/Dockerfile b/1.6/wheezy/Dockerfile
similarity index 87%
copy from 1.5/wheezy/Dockerfile
copy to 1.6/wheezy/Dockerfile
index 381df5f..945ea89 100644
--- a/1.5/wheezy/Dockerfile
+++ b/1.6/wheezy/Dockerfile
@@ -8,9 +8,9 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
                make \
        && rm -rf /var/lib/apt/lists/*
 
-ENV GOLANG_VERSION 1.5.2
+ENV GOLANG_VERSION 1.6beta1
 ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz
-ENV GOLANG_DOWNLOAD_SHA1 cae87ed095e8d94a81871281d35da7829bd1234e
+ENV GOLANG_DOWNLOAD_SHA1 5c02222a5ab348ae0f9244df95dea71781953749
 
 RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
        && echo "$GOLANG_DOWNLOAD_SHA1  golang.tar.gz" | sha1sum -c - \
diff --git a/go-wrapper b/1.6/wheezy/go-wrapper
similarity index 100%
copy from go-wrapper
copy to 1.6/wheezy/go-wrapper
```

**Comment by pwaller** [comment]
Hey @tianon, when will this appear on the docker hub?

**Comment by tianon** [comment]
It was waiting on https://github.com/docker-library/official-images/issues/1290 and should be long since up now; sorry for the response delay!

**Comment by pwaller** [comment]
Thanks @tianon I did happen to see it :)

**Pull request merged**
