### PR TITLE
LICENSE 2018

### PR DESCRIPTION
**Pull request by sakajunquality**
update LICENSE to the latest

### CODE REVIEW

**Comment by yosifkit** [comment]
Seems reasonable (though also silly seeing how git tracks all changes so every commit means the project was "published" again and so it should always be the current year).  Useful info: https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/

cc @tianon

**Comment by tianon** [comment]
Yeah, I tend to agree -- updating copyright ending years seems like busywork.  It's my understanding that generally, the meaningful bit of information is the starting year.

**Comment by sakajunquality** [comment]
@tianon @yosifkit 
Just left the year of beginning

https://opensource.org/licenses/BSD-3-Clause

**Comment by tianon** [comment]
Thanks!

**Pull request merged**
