### PR TITLE
Add 1.5-wheezy version

### PR DESCRIPTION
**Pull request by Luit**
I'm not sure if what's in this PR is enough to add this version, but the intention was to add a 1.5-wheezy build. 

I would love to have this because we build a Go application that will run on Debian Wheezy, and we like to build a .deb package using Docker.

### CODE REVIEW

**Comment by yosifkit** [comment]
Seems fine to me. Could you add this new variant to the [`.travis.yml`](https://github.com/docker-library/golang/blob/master/.travis.yml#L7)?

**Comment by Luit** [comment]
Like so?

**Comment by yosifkit** [comment]
:+1: LGTM

**Comment by tianon** [comment]
LGTM

**Pull request merged**
