### PR TITLE
Add explicit support for Windows Server 1709

### PR DESCRIPTION
**Pull request by tianon**
See also https://github.com/docker-library/hello-world/pull/41.

### CODE REVIEW

**Comment by tianon** [comment]
```diff
$ diff -u <(bashbrew cat golang) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2017-11-22 14:12:34.105585853 -0800
+++ /dev/fd/62	2017-11-22 14:12:34.106585824 -0800
@@ -12,18 +12,33 @@
 GitCommit: bb5a9205c84b1af7daea647e144f2517497cc7ef
 Directory: 1.9/alpine3.6
 
-Tags: 1.9.2-windowsservercore, 1.9-windowsservercore, 1-windowsservercore, windowsservercore
-SharedTags: 1.9.2, 1.9, 1, latest
+Tags: 1.9.2-windowsservercore-ltsc2016, 1.9-windowsservercore-ltsc2016, 1-windowsservercore-ltsc2016, windowsservercore-ltsc2016
+SharedTags: windowsservercore, 1.9.2, 1.9, 1, latest
 Architectures: windows-amd64
-GitCommit: cffcff7fce7f6b6b5c82fc8f7b3331a10590a661
-Directory: 1.9/windows/windowsservercore
-Constraints: windowsservercore
+GitCommit: 2a95abb5f5ce6937f184830bb43638fc5142a5ee
+Directory: 1.9/windows/windowsservercore-ltsc2016
+Constraints: windowsservercore-ltsc2016
 
-Tags: 1.9.2-nanoserver, 1.9-nanoserver, 1-nanoserver, nanoserver
+Tags: 1.9.2-windowsservercore-1709, 1.9-windowsservercore-1709, 1-windowsservercore-1709, windowsservercore-1709
+SharedTags: windowsservercore, 1.9.2, 1.9, 1, latest
 Architectures: windows-amd64
-GitCommit: cffcff7fce7f6b6b5c82fc8f7b3331a10590a661
-Directory: 1.9/windows/nanoserver
-Constraints: nanoserver
+GitCommit: 2a95abb5f5ce6937f184830bb43638fc5142a5ee
+Directory: 1.9/windows/windowsservercore-1709
+Constraints: windowsservercore-1709
+
+Tags: 1.9.2-nanoserver-sac2016, 1.9-nanoserver-sac2016, 1-nanoserver-sac2016, nanoserver-sac2016
+SharedTags: nanoserver
+Architectures: windows-amd64
+GitCommit: 2a95abb5f5ce6937f184830bb43638fc5142a5ee
+Directory: 1.9/windows/nanoserver-sac2016
+Constraints: nanoserver-sac2016
+
+Tags: 1.9.2-nanoserver-1709, 1.9-nanoserver-1709, 1-nanoserver-1709, nanoserver-1709
+SharedTags: nanoserver
+Architectures: windows-amd64
+GitCommit: 2a95abb5f5ce6937f184830bb43638fc5142a5ee
+Directory: 1.9/windows/nanoserver-1709
+Constraints: nanoserver-1709
 
 Tags: 1.8.5-stretch, 1.8-stretch
 Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
@@ -50,15 +65,30 @@
 GitCommit: 132cd70768e3bc269902e4c7b579203f66dc9f64
 Directory: 1.8/onbuild
 
-Tags: 1.8.5-windowsservercore, 1.8-windowsservercore
-SharedTags: 1.8.5, 1.8
+Tags: 1.8.5-windowsservercore-ltsc2016, 1.8-windowsservercore-ltsc2016
+SharedTags: windowsservercore, 1.8.5, 1.8
 Architectures: windows-amd64
-GitCommit: cffcff7fce7f6b6b5c82fc8f7b3331a10590a661
-Directory: 1.8/windows/windowsservercore
-Constraints: windowsservercore
+GitCommit: 2a95abb5f5ce6937f184830bb43638fc5142a5ee
+Directory: 1.8/windows/windowsservercore-ltsc2016
+Constraints: windowsservercore-ltsc2016
 
-Tags: 1.8.5-nanoserver, 1.8-nanoserver
+Tags: 1.8.5-windowsservercore-1709, 1.8-windowsservercore-1709
+SharedTags: windowsservercore, 1.8.5, 1.8
 Architectures: windows-amd64
-GitCommit: cffcff7fce7f6b6b5c82fc8f7b3331a10590a661
-Directory: 1.8/windows/nanoserver
-Constraints: nanoserver
+GitCommit: 2a95abb5f5ce6937f184830bb43638fc5142a5ee
+Directory: 1.8/windows/windowsservercore-1709
+Constraints: windowsservercore-1709
+
+Tags: 1.8.5-nanoserver-sac2016, 1.8-nanoserver-sac2016
+SharedTags: nanoserver
+Architectures: windows-amd64
+GitCommit: 2a95abb5f5ce6937f184830bb43638fc5142a5ee
+Directory: 1.8/windows/nanoserver-sac2016
+Constraints: nanoserver-sac2016
+
+Tags: 1.8.5-nanoserver-1709, 1.8-nanoserver-1709
+SharedTags: nanoserver
+Architectures: windows-amd64
+GitCommit: 2a95abb5f5ce6937f184830bb43638fc5142a5ee
+Directory: 1.8/windows/nanoserver-1709
+Constraints: nanoserver-1709
```

**Comment by tianon** [comment]
```diff
$ diff -u <(bashbrew cat golang) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2017-11-22 14:15:52.224903305 -0800
+++ /dev/fd/62	2017-11-22 14:15:52.225903276 -0800
@@ -12,18 +12,26 @@
 GitCommit: bb5a9205c84b1af7daea647e144f2517497cc7ef
 Directory: 1.9/alpine3.6
 
-Tags: 1.9.2-windowsservercore, 1.9-windowsservercore, 1-windowsservercore, windowsservercore
-SharedTags: 1.9.2, 1.9, 1, latest
+Tags: 1.9.2-windowsservercore-ltsc2016, 1.9-windowsservercore-ltsc2016, 1-windowsservercore-ltsc2016, windowsservercore-ltsc2016
+SharedTags: windowsservercore, 1.9.2, 1.9, 1, latest
 Architectures: windows-amd64
-GitCommit: cffcff7fce7f6b6b5c82fc8f7b3331a10590a661
-Directory: 1.9/windows/windowsservercore
-Constraints: windowsservercore
+GitCommit: 4c111083e9764d83578eb79766263c8ca76f57ef
+Directory: 1.9/windows/windowsservercore-ltsc2016
+Constraints: windowsservercore-ltsc2016
 
-Tags: 1.9.2-nanoserver, 1.9-nanoserver, 1-nanoserver, nanoserver
+Tags: 1.9.2-windowsservercore-1709, 1.9-windowsservercore-1709, 1-windowsservercore-1709, windowsservercore-1709
+SharedTags: windowsservercore, 1.9.2, 1.9, 1, latest
 Architectures: windows-amd64
-GitCommit: cffcff7fce7f6b6b5c82fc8f7b3331a10590a661
-Directory: 1.9/windows/nanoserver
-Constraints: nanoserver
+GitCommit: 4c111083e9764d83578eb79766263c8ca76f57ef
+Directory: 1.9/windows/windowsservercore-1709
+Constraints: windowsservercore-1709
+
+Tags: 1.9.2-nanoserver-sac2016, 1.9-nanoserver-sac2016, 1-nanoserver-sac2016, nanoserver-sac2016
+SharedTags: nanoserver
+Architectures: windows-amd64
+GitCommit: 4c111083e9764d83578eb79766263c8ca76f57ef
+Directory: 1.9/windows/nanoserver-sac2016
+Constraints: nanoserver-sac2016
 
 Tags: 1.8.5-stretch, 1.8-stretch
 Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
@@ -50,15 +58,23 @@
 GitCommit: 132cd70768e3bc269902e4c7b579203f66dc9f64
 Directory: 1.8/onbuild
 
-Tags: 1.8.5-windowsservercore, 1.8-windowsservercore
-SharedTags: 1.8.5, 1.8
+Tags: 1.8.5-windowsservercore-ltsc2016, 1.8-windowsservercore-ltsc2016
+SharedTags: windowsservercore, 1.8.5, 1.8
 Architectures: windows-amd64
-GitCommit: cffcff7fce7f6b6b5c82fc8f7b3331a10590a661
-Directory: 1.8/windows/windowsservercore
-Constraints: windowsservercore
+GitCommit: 4c111083e9764d83578eb79766263c8ca76f57ef
+Directory: 1.8/windows/windowsservercore-ltsc2016
+Constraints: windowsservercore-ltsc2016
 
-Tags: 1.8.5-nanoserver, 1.8-nanoserver
+Tags: 1.8.5-windowsservercore-1709, 1.8-windowsservercore-1709
+SharedTags: windowsservercore, 1.8.5, 1.8
 Architectures: windows-amd64
-GitCommit: cffcff7fce7f6b6b5c82fc8f7b3331a10590a661
-Directory: 1.8/windows/nanoserver
-Constraints: nanoserver
+GitCommit: 4c111083e9764d83578eb79766263c8ca76f57ef
+Directory: 1.8/windows/windowsservercore-1709
+Constraints: windowsservercore-1709
+
+Tags: 1.8.5-nanoserver-sac2016, 1.8-nanoserver-sac2016
+SharedTags: nanoserver
+Architectures: windows-amd64
+GitCommit: 4c111083e9764d83578eb79766263c8ca76f57ef
+Directory: 1.8/windows/nanoserver-sac2016
+Constraints: nanoserver-sac2016
```

**Comment by tianon** [comment]
Cross-linking https://github.com/appveyor/ci/issues/1885 (which is included in a comment here in `update.sh`) just for visibility/reference -- AppVeyor doesn't (yet) support 1709, so we can't auto-test those variants here.

**Comment by StefanScherer** [comment]
😍

**Pull request merged**
