### PR TITLE
Golang 1.12 released

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

xref: https://blog.golang.org/go1.12

### CODE REVIEW

**Comment by bithavoc** [comment]
Can we get this merged?

**Comment by tao12345666333** [comment]
maybe wait for @tianon . :heart:

**Comment by tianon** [comment]
(Merging since original commit's CI was green and all my changes are either deletions or things untested by Travis.)

**Comment by JulienBreux** [comment]
Hi, sorry, but non-updated on https://hub.docker.com/_/golang?tab=tags

?

Thanks 🍻

**Comment by techknowlogick** [comment]
@JulienBreux you'll need to wait for https://github.com/docker-library/official-images/pull/5473

**Comment by bmhatfield** [comment]
@JulienBreux (for future reference, it's mentioned in this repo's README about the image shipping process): [here](https://github.com/docker-library/golang#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet)

**Comment by JulienBreux** [comment]
@techknowlogick thanks 😊
@bmhatfield my apologies 🙏🏻

**Comment by tao12345666333** [comment]
Thanks @tianon

**Pull request merged**
